### PR TITLE
WIP Update composer scaffolding repo with specific package version numbers that are compatible with composer 2.0

### PR DESCRIPTION
**Pull request by trackleft**
Still need to update drupal-console-extend-plugin once this is merged https://github.com/hechoendrupal/drupal-console-extend-plugin/pull/25/files

### CODE REVIEW

**Comment by trackleft** [comment]
Relevant issue https://github.com/hechoendrupal/drupal-console-extend-plugin/issues/23

**Comment by trackleft** [comment]
Related https://github.com/az-digital/az_quickstart/issues/349

**Comment by trackleft** [comment]
Relevant https://github.com/az-digital/az_quickstart/issues/349

**Review by tadean — APPROVED** [review]
Built successfully locally (with composer 2 and composer 1)

**Review by joeparsons — APPROVED** [review]

**Pull request merged**
