### PR TITLE
az-digital/az_quickstart#1491: Temporarily remove assset-packagist as composer repo.

### PR DESCRIPTION
**Pull request by joeparsons**
See az-digital/az_quickstart#1491

### CODE REVIEW

**Review by mmunro-ltrr — APPROVED** [review]

**Review by jwmoore1 — APPROVED** [review]

**Comment by jwmoore1** [comment]
@mmunro-ltrr Since this is Joe's PR, do you want to go ahead and merge it?

**Comment by joeparsons** [comment]
FWIW, merging this PR will only "fix" composer installs of the `dev-main` version of Quickstart (and only if the corresponding [Quickstart PR](az-digital/az_quickstart#1492) is merged as well.

We'll also need to backport both PRs to the `2.2.x` and `2.1.x` branches in both repos and create a new Quickstart patch release to "fix" non dev builds of Quickstart...

The Pantheon upstream will also need to be updated.

This is not a real long-term solution to the problem, either just fix to prevent composer builds from failing.  This definitely has bad side affects for Quickstart features as is.

**Comment by jwmoore1** [comment]
Based on the [info](https://github.com/hiqdev/asset-packagist/issues/146) that the managing team is from Ukraine, what are possible long term solutions we could implement if asset-packagest stays down?

**Comment by joeparsons** [comment]
> Based on the [info](https://github.com/hiqdev/asset-packagist/issues/146) that the managing team is from Ukraine, what are possible long term solutions we could implement if asset-packagest stays down?

One solution we could consider would be to mirror the git repos for all of the NPM/bower packages we are using in our own GitHub org and add composer.json files to them...  This would require adding a bunch of additional `repository` entries to our scaffolding (and Pantheon upstream) `composer.json` files.

**Comment by SilverFire** [comment]
Asset-packagist is up, sorry for the troubles. You can find an explanation in the original issue: https://github.com/hiqdev/asset-packagist/issues/146#issuecomment-1106742011

**Pull request merged**
